### PR TITLE
Synced Configs

### PR DESCRIPTION
**Pull request by Entity378**
I added the possibility of configuring some aspects of the Motion Tracker. 
The configs synchronize with those of the host.

### CODE REVIEW

**Comment by CyanBlob** [comment]
This looks great! Have you tested it in multiplayer?

**Comment by Entity378** [comment]
> This looks great! Have you tested it in multiplayer?

I tested it but we already had all the same configs.
Unfortunately finding people to test the mod with isn't easy for me, however one thing I'm sure of is that the configs are generated and loaded by the mod

**Comment by Entity378** [comment]
> > This looks great! Have you tested it in multiplayer?
> 
> I tested it but we already had all the same configs. Unfortunately finding people to test the mod with isn't easy for me, however one thing I'm sure of is that the configs are generated and loaded by the mod

I tried it now and apparently it doesn't work :) (I hate my life)
idk if you have time, but you could try taking a look at it to help me figure out what's wrong pls

**Comment by Entity378** [comment]
I tried changing/adding something but it doesn't seem to work anyway. I could really use a hand.

**Comment by Entity378** [comment]
I tried changing/adding something but it doesn't seem to work anyway. I need help anyway

**Comment by Entity378** [comment]
Maybe I found the problem but I don't have time to test it since it's 01:10 AM where I live.

**Comment by CyanBlob** [comment]
Hi @Entity378. Did you close this PR because you don't have time to finish it? Or for some other reason?

**Comment by Entity378** [comment]
@CyanBlob  Let's say I'm trying to take a sort of "break". Apart from that, i don't have any way to test whether the networking works, it is difficult for me to make a PR that actually works. In this regard, I had thought of uploading a temporary version with the changeable configs on Thunderstore (obviously giving you the credits) in the hope that someone would do some tests to see if the networking actually works. When someone gives me confirmation that it works, or if i can find someone to test it, I'll do a PR one last time. In any case, i hope that having created a version with the config and having uploaded it hasn't bothered you, in case, i will proceed to mark it as deprecated (Which i would do anyway once i understand if the Networking works). And sorry it took me so long to reply

**Comment by Entity378** [comment]
small update, I think I found and solved the problem for config sync. It occurred to me that I can use the LAN function of the game by running 2 instances of it to test if the mod works (I'm stupid for not thinking of this before)

**Pull request closed without merging**
